name: Node.js Package

on: 
  push: 
    branches:
      - refs/tags/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm install typescript
      - run: tsc
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

#  publish-gpr:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 12
#          registry-url: https://npm.pkg.github.com/
#          scope: '@your-github-username'
#      - run: npm publish --access public
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
